### ISSUE TITLE
Query string key encoding issues

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/query-string#14]
I have the following piece of Blade code:

```html
<ul class="flex">
    <li>
        <a href="{{ $queryString->filter('status', 'sent') }}">
            Sent ({{ $sentCampaignsCount }})
        </a>
    </li>
    <li>
        <a href="{{ $queryString->filter('status', 'draft') }}">
            Draft ({{ $draftCampaignsCount }})
        </a>
    </li>
</ul>
```

When on `/campaigns` and clicking "Sent", it sends me to `/campaigns?filter[status]=sent`.

When on `/campaigns?filter[status]=sent` and clicking "Draft", it sends me to `/campaigns?filter%5Bstatus%5D=sent&filter[status]=draft`.

**Comment by brendt** [comment]
Where does `$queryString` come from? In a Laravel context I register it in the container like so (notice the URL decode): https://github.com/brendt/aggregate.stitcher.io/blob/master/app/App/Providers/AppServiceProvider.php#L55-L60

And I have these helper functions: https://github.com/brendt/aggregate.stitcher.io/blob/master/app/helpers.php#L24-L104

I think a `laravel-query-string` package would be the right place to solve this, though I'm not sure it's worth packaging it all up for so little functionality…

**Comment by sebastiandedeyne** [comment]
Didn't know I had to do the URL decode myself, that solved the issue 👍
