### ISSUE TITLE
QueryString toggle method trims from the value if it has '=' symbol in it

### ISSUE THREAD

**Issue by galkrisztina** [spatie/query-string#16]
Hello! I am using your package for creating a redirect url from my API in case of a social login. I am using Laravel Socialite for it, and in case of the Facebook authentication, the provider gives back an object where the profile picture of the user consists of a link which contains `=` symbol in it. The problem is that the `Ast` class's `buildNode` private method's `[$name, $value] = explode('=', $definition);` row trims form this link beginning of the second `=`.  If I give a third parameter for the `explode` method to limit it for `2`, then it works fine. 

My question is that do you have a reason to not limit that `explode`? If so, do you have any solution for this problem, please? 

Thank you, Krisztina.

**Comment by freekmurze** [comment]
I haven't come across this issue myself. Feel free to PR a fix, make sure to include tests 👍
